INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('code@gmail.com','Dev Code','123456',1,'Codero')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Marta3@gmail.com','Ubaldo','fcmAVYGhmAYYKPR',1,'Dickens')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Verona.Ruecker@hotmail.com','Deonte','rZBFJn2zd1dM3kc',1,'Ryan')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Devyn36@gmail.com','Kobe','GFpQg7AXSDcdVEL',1,'Bode')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Dudley_Olson@yahoo.com','Antoinette','RmL6nu3yz9pms9D',1,'Von')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Dennis8@hotmail.com','Cristopher','vPSjIXdysCSL779',1,'McClure')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Kara_Ortiz@hotmail.com','Cassie','WKGq02ZRLG384Rc',1,'Vandervort')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Amelia_Howell20@hotmail.com','Edmund','BgGOiCKNJR3CAv6',1,'Veum')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Clementine.Schowalter73@yahoo.com','Kailee','tLwKkzU0tL2AO7w',1,'Brekke')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Domenick3@yahoo.com','Rahsaan','DhCTmBu_yx7gSJq',1,'Ebert')
INSERT INTO users (email,name,password,is_enabled,last_name) VALUES ('Margarita.Borer4@gmail.com','Lilliana','CyoqABwY0acVUAB',1,'Breitenberg')

INSERT INTO roles (name) VALUES ('ADMIN')
INSERT INTO roles (name) VALUES ('USER')
INSERT INTO roles (name) VALUES ('GUEST')

INSERT INTO user_has_roles (user_id,role_id) VALUES (1,1)
INSERT INTO user_has_roles (user_id,role_id) VALUES (2,2)
INSERT INTO user_has_roles (user_id,role_id) VALUES (3,3)